# soltybet-v2/smart-contract/Anchor.toml
[features]
seeds = false
skip-lint = false

[programs.mainnet]
deposit_gate = "5awMTFDmJv3EXEPstpJKD6fJ6FrLfcBw5Ek5CeutvKcM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
